FROM golang:1.6

MAINTAINER Felix Abecassis "fabecassis@nvidia.com"

RUN go get github.com/flx42/boom

COPY images /images

CMD boom -readall -c ${CONCURRENCY} -n ${REQUESTS} -m POST -d @/images/2.jpg http://localhost:8000/api/classify
